import image from '../assets/images/png/ice cream.png';
import productImage from '../assets/images/png/product ice cream.png';

const cardsArr = [
  {
    image,
    productImage,
    code: 'SKU: BXD100BLK',
    title: 'Snow Tender Ice Cream',
    descr1: 'Chocolate ice cream has a bright, rich and refreshing taste of the ingredient it contains. Thanks to liquid nitrogen shock freezing (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, all the flavors, vitamins and nutrients are preserved by 99%.',
    descr2: 'Blast freezing with liquid nitrogen (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, preserving all the flavors, vitamins and nutrients by 99%.',
    price: '243.00',
    id: 1,
  },
  {
    image,
    productImage,
    code: 'SKU: BXD100BLK',
    title: 'Snow Tender Ice Cream',
    descr1: 'Chocolate ice cream has a bright, rich and refreshing taste of the ingredient it contains. Thanks to liquid nitrogen shock freezing (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, all the flavors, vitamins and nutrients are preserved by 99%.',
    descr2: 'Blast freezing with liquid nitrogen (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, preserving all the flavors, vitamins and nutrients by 99%.',
    price: '243.00',
    id: 2,
  },
  {
    image,
    productImage,
    code: 'SKU: BXD100BLK',
    title: 'Snow Tender Ice Cream',
    descr1: 'Chocolate ice cream has a bright, rich and refreshing taste of the ingredient it contains. Thanks to liquid nitrogen shock freezing (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, all the flavors, vitamins and nutrients are preserved by 99%.',
    descr2: 'Blast freezing with liquid nitrogen (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, preserving all the flavors, vitamins and nutrients by 99%.',
    price: '243.00',
    id: 3,
  },
  {
    image,
    productImage,
    code: 'SKU: BXD100BLK',
    title: 'Snow Tender Ice Cream',
    descr1: 'Chocolate ice cream has a bright, rich and refreshing taste of the ingredient it contains. Thanks to liquid nitrogen shock freezing (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, all the flavors, vitamins and nutrients are preserved by 99%.',
    descr2: 'Blast freezing with liquid nitrogen (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, preserving all the flavors, vitamins and nutrients by 99%.',
    price: '243.00',
    id: 4,
  },
  {
    image,
    productImage,
    code: 'SKU: BXD100BLK',
    title: 'Snow Tender Ice Cream',
    descr1: 'Chocolate ice cream has a bright, rich and refreshing taste of the ingredient it contains. Thanks to liquid nitrogen shock freezing (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, all the flavors, vitamins and nutrients are preserved by 99%.',
    descr2: 'Blast freezing with liquid nitrogen (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, preserving all the flavors, vitamins and nutrients by 99%.',
    price: '243.00',
    id: 5,
  },
  {
    image,
    productImage,
    code: 'SKU: BXD100BLK',
    title: 'Snow Tender Ice Cream',
    descr1: 'Chocolate ice cream has a bright, rich and refreshing taste of the ingredient it contains. Thanks to liquid nitrogen shock freezing (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, all the flavors, vitamins and nutrients are preserved by 99%.',
    descr2: 'Blast freezing with liquid nitrogen (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, preserving all the flavors, vitamins and nutrients by 99%.',
    price: '243.00',
    id: 6,
  },
  {
    image,
    productImage,
    code: 'SKU: BXD100BLK',
    title: 'Snow Tender Ice Cream',
    descr1: 'Chocolate ice cream has a bright, rich and refreshing taste of the ingredient it contains. Thanks to liquid nitrogen shock freezing (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, all the flavors, vitamins and nutrients are preserved by 99%.',
    descr2: 'Blast freezing with liquid nitrogen (-193°C), which freezes all the ingredients instantly and gives the ice cream an amazingly delicate texture, preserving all the flavors, vitamins and nutrients by 99%.',
    price: '243.00',
    id: 7,
  },
];

export default cardsArr;
